credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$zncKJJemGNF9T0UNn/mEq.hUKFgDVxWFOCuBP5nGJadaIWa4vWqXG
      # Ersetze den Hash durch einen echten Hash, z.B. mit:
      # import bcrypt
      # print(bcrypt.hashpw(b'test1234', bcrypt.gensalt()).decode())
cookie:
  expiry_days: 365
  key: my_signature_key
  name: my_cookie_name
preauthorized:
  emails:
    - admin@example.com
